### ISSUE TITLE
Values for confidence and rating

### ISSUE THREAD

**Issue by nikitamehrotra12** [FAU-Inf2/sesame#1]
Hi,

Can you please share the mapping of the values of confidence and rating i.e. what does 0 mean low confidence or high confidence and agree or disagree.

**Comment by mskamp** [comment]
In commit 0f508bd, I added an explanation for the numeric values. Please let me know if there is still something that is unclear.

**Comment by nikitamehrotra12** [comment]
Thanks for the explanation.
